tup=(1,2,3)
tup1=(1,2,3,("cat","apple","banana",4),66)
for a in tup:
    print(a,end=" ")
print()
print(len(tup))
print(tup)
print(tup[2])
tup=tup+(7,8,)
print(tup)
print(tup1[3][2])
print(tup[1:2])
print(tup1[3:])
print(tup1[:3])
print(tup1.index(66))
